### ISSUE TITLE
GSE accessions are missing

### ISSUE THREAD

**Issue by inutano** [markziemann/dee2#75]
Hi, thank you for providing a great resource! I've tried the programmatic access to the DEE2 data following the procedure in [`AccessDEEfromR.md`](https://github.com/markziemann/dee2/blob/master/AccessDEEfromR.md), and found the downloaded metadata tsv files do not have GSE accession IDs. I've tried with `getDee2Metadata()` for all the species and none did have GSE accessions in the downloaded `tsv.cut` file. Is this an error of the data, or something has changed? This prevented me to follow the example - I've got expression data by using SRA project accessions though.

**Comment by markziemann** [comment]
Hello @inutano due to the ways in which SRA interacts with GEO, the GEO series accessions may not be searchable anymore. This issues came about because SRAdbV2 was no longer supported. (We hope to have a better source of metadata soon...) 
Therefore the easiest way for you to find the data you need is to get the SRA project accession number for the study. Use your GEO series accession number to search GEO and then you will find a link to the SRA project accession number which probably begins with SRPXXX 
Then you can use that number to search the metadata using the R package, the web interface or even to download the whole project if it is available under http://dee2.io/huge/ 
Let me know if you still cannot find the dataset you require.

**Comment by inutano** [comment]
Thanks @markziemann !! OK, so I'll use SRA IDs instead - actually I'm mainly using SRA identifiers so will have no problem, but just had an issue when I tried to follow the example.

BTW I'm maintaining a similar database called [chip-atlas](https://chip-atlas.org) and would like to integrate the RNA-Seq data in DEE2 and the ChIP-Seq data in our ChIP-Atlas. I'll let you know when I got an interesting results!

**Comment by markziemann** [comment]
Glad to be of service! I noticed there was a permissions problem with some of the human data that got uploaded yesterday. Not sure if you were impacted but it's fixed now.
I'm super excited to hear about your new resource! I had heard about CistromeDB and ReMap before but didn't know about ChIP-Atlas. I look forward to using it!

**Comment by inutano** [comment]
I've been working with the SRA data since its beginning, so I know there're always some issues ;) I'm sure that maintaining this is not that easy as well - thanks for your hard work to keep this up to date! 

I'm closing this issue, but I'd recommend you to fix or put a message on [AccessDEEfromR.md](https://github.com/markziemann/dee2/blob/master/AccessDEEfromR.md) so that people won't get confused!

**Comment by markziemann** [comment]
Hi Tazro,

The DEE2 team have developed a new feature that lets users request a SRA
transcriptome project to be completed in demand. You will receive an email
when it's ready.

Give it a try at http://dee2.io/request.html and let us know if you have
any suggestions on the feature.

Thanks,
Mark Z

**Comment by inutano** [comment]
Fantastic! I'll share this with my colleagues, this would be a great help for all the users of the SRA. Thank you very much for your effort, Mark!
