### ISSUE TITLE
dee2.io website is down

### ISSUE THREAD

**Issue by maciejmotyka** [markziemann/dee2#97]
Hi Mark!
The website is not responding, which also renders the R package unusable.

I'm using the dockerized pipeline in the meantime, but I need a quite a lot of studies, so hoping for a quick fix.

**Comment by markziemann** [comment]
Hello Maciej, the site suffered a cybersecurity issue and so it was taken down by the cloud provider. I've since built a new webservice from scratch (with https this time) but yet to connect up the volume containing the expression data.
I hope to have the data available again in 1 week's time.
I'm sorry for the inconvenience caused.

**Comment by markziemann** [comment]
The site is back up now and should be working
